{% set name = "mkdocstrings" %}
{% set version = "0.26.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-{{ version }}.tar.gz
  sha256: 34a8b50f1e6cfd29546c6c09fbe02154adfb0b361bb758834bf56aa284ba876e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - pdm-backend
  run:
    - python >=3.8,<4.0
    - click >=7.0
    - jinja2 >=2.11.1
    - markdown >=3.6
    - markupsafe >=1.1
    - mkdocs >=1.4
    - mkdocs-autorefs >=1.2
    - platformdirs >=2.2.0
    - pymdown-extensions >=6.3
    - importlib-metadata >=4.6
    - typing-extensions >=4.1

test:
  imports:
    - mkdocstrings
    - mkdocstrings.handlers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/mkdocstrings
  doc_url: https://mkdocstrings.github.io
  summary: Automatic documentation from sources, for MkDocs.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
