{% set name = "mkdocstrings" %}
{% set version = "0.28.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-{{ version }}.tar.gz
  sha256: df20afef1eafe36ba466ae20732509ecb74237653a585f5061937e54b553b4e0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm-backend
  run:
    - python >={{ python_min }},<4.0
    - click >=7.0
    - jinja2 >=2.11.1
    - markdown >=3.6
    - markupsafe >=1.1
    - mkdocs >=1.4
    - mkdocs-autorefs >=1.3
    - mkdocs-get-deps >=0.2
    - pymdown-extensions >=6.3
    - importlib-metadata >=4.6
    - typing-extensions >=4.1

test:
  imports:
    - mkdocstrings
    - mkdocstrings.handlers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mkdocstrings/mkdocstrings
  doc_url: https://mkdocstrings.github.io
  summary: Automatic documentation from sources, for MkDocs.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
