{% set name = "mkdocstrings" %}
{% set version = "0.22.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-{{ version }}.tar.gz
  sha256: 82a33b94150ebb3d4b5c73bab4598c3e21468c79ec072eff6931c8f3bfc38256

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - pdm-backend
  run:
    - python >=3.7,<4.0
    - jinja2 >=2.11.1
    - markdown >=3.3
    - markupsafe >=1.1
    - mkdocs >=1.2
    - mkdocs-autorefs >=0.3.1
    - pymdown-extensions >=6.3
    - importlib-metadata>=4.6
    - typing-extensions >=4.1

test:
  imports:
    - mkdocstrings
    - mkdocstrings.handlers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/mkdocstrings
  doc_url: https://mkdocstrings.github.io
  summary: Automatic documentation from sources, for MkDocs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
    - hadim
